### ISSUE TITLE
Sort out existing versions

### ISSUE THREAD

**Issue by davidanthoff** [JuliaStats/Lora.jl#104]
There still seems to be some discrepancies between the tags in this repo and what is registered in METADATA.

Specifically: there is a tag v0.3.3 in the repo, but no version 0.3.3 is registered in METADATA. I think that tag should just be deleted in the Lora repo.

Also, looking at the various branches and history, I'm kind of confused what is going on. It looks to me that the new 0.5.0 work is not based on the 0.4.x branch, but split way earlier? But then the v0.3.2 release seems to branch off that branch that eventually became 0.5.0?

Finally, I'm on julia 0.3.x, so I get the commit that is tagged as v0.3.3 right now in the repo with a ``Pkg.add``. Is this because Lora 0.4.x is julia 0.4 only?

**Comment by scidom** [comment]
Hi @davidanthoff, you are right Lora 0.4.x is Julia 0.4 only and Lora 0.3.x is Julia 0.3 only.

I don't know why 0.3.3 appears to be a git tag, I will delete this one as it shouldn't be there.

As of branch 0.5.0, it is not part of metadata because it is the branch I have been working on over the last two months and still work on it. Since it is a dev branch (and its tagging may change when it is merged), I would suggest not to pay too much attention to its current temporary tag.

**Comment by scidom** [comment]
I deleted the 0.3.3 git tag from the remote repo, it should be sorted now - let me know if you run into any problems.

**Comment by davidanthoff** [comment]
Ok, cool, thanks. I guess I was just confused that 0.5.0 is 50 commits behind master...

**Comment by scidom** [comment]
Great, @davidanthoff. Yes, I've noticed this and it seems confusing indeed. Nevertheless, it is just an artifact in the sense that I started development in 0.5.0 from a clean slate (deleted all previous code temporarily), so 0.5.0 has no dependence at all on previous branches.
