### ISSUE TITLE
Bug in MCLikelihood

### ISSUE THREAD

**Issue by scidom** [JuliaStats/Lora.jl#77]
@fredo-dedup there is a bug in `MCLikelihood`. I will update the code as soon as I find the fix, unless you are faster than me. Here is the bug:

```
using Lora
MCLikelihood(x->x)
```

This returns

```
ERROR: TypeError: non-boolean (Array{Bool,1}) used in boolean context
 in call at C:\Users\theodore\.julia\v0.4\Lora\src\models/MCLikelihood.jl:57
 in MCLikelihood at C:\Users\theodore\.julia\v0.4\Lora\src\models/MCLikelihood.jl:138
```

**Comment by fredo-dedup** [comment]
The function x -> x is not turned into a function on a Vector{Float64} (line 46 in MCLikelihood.jl) because it is not generic (test line 44). Later in the constructor, when testing if `init` is in the support (line 57), it returns `init` (a vector) instead of a Float64 which generates the error.
Using a non anonymous function `g(x) = x` will produce the same error. In fact the only case where we can catch and correct the problem in line 46 is when the generic function has a typed parameter  `g(x::Float64) = x`. This could be extended to anonymous functions but would require AFAICT parsing its AST.
From the point of view of the constructor, it seems difficult to know if the lik function (both generic and anonymous) is meant to be called with a Float64 or a Vector[Float64] because `init` is already turned into a Vector. May be we should allow `init` to be a Float64 (or a Real) and use that to decide to transform functions.
Note that this would require doing `MCLikelihood(x->x, init=1.)` because the default for init is `[1.0]` (a vector).

**Comment by scidom** [comment]
The idea of being more specific regarding the type of function arguments sounds good to me, since this may have some performance benefits too. Furthermore, it would be nice to have "function types", which would give more enriched functional programming capabilities (I think Julia doesn't offer yet "function types" such as "(Float64) => Float64" for ex).

Your second suggestion sounds also good, it may be useful to allow `init` to be `Union(Float64, Vector{Float64})`, which relates to the more general question on whether we want Lora to operate only on vectors of floats or on floats too as well...

**Comment by scidom** [comment]
This is now irrelevant, as parameters are used instead of MCLikelihood.
